name: Build and Publish Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup, build, and publish with gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: build publish
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  prune_versions:
    needs: [release]
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Read properties from gradle.properties
        run: |
            MC_VERSION=$(grep "^minecraft_version=" gradle.properties | cut -d'=' -f2)
            MOD_ID=$(grep "^mod_id=" gradle.properties | cut -d'=' -f2)
            echo "mc_version=$MC_VERSION" >> $GITHUB_ENV
            echo "mod_id=$MOD_ID" >> $GITHUB_ENV

      - name: Keep only latest 4 versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: "liedge.${{ env.mod_id }}-${{ env.mc_version }}"
          package-type: 'maven'
          min-versions-to-keep: 4